diary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('entry.urls'))
]

entry/urls.py
from django.urls import path
from . import views

app_name = 'entry'

urlpatterns = [
    path('',views.home_view,name="home" ),
    path('entry/',views.entry_view,name="entr"),
]

entry/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):
	name = models.CharField(max_length=20)
	story = models.TextField()
	date = models.DateTimeField(auto_now_add=True, blank=True)
		
	def __str__(self):
		return self.name

	def snippet(self):
		return self.story[:100] + '...'

entry/forms.py
from django.forms import ModelForm
from .models import Entry


class EntryForm(ModelForm):
	class Meta:
		model = Entry
		fields = ('name','story',)

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.fields['name'].widget.attrs.update({'class':'form-control','placeholder':'Entry Title'})
		self.fields['story'].widget.attrs.update({'class':'form-control','placeholder':'Enter your Thoughts...'})

entry/views.py
from django.shortcuts import render,redirect
from .models import Entry
from .forms import EntryForm

# Create your views here.
def home_view(request):
	entries = Entry.objects.all().order_by('-date')
	return render(request,'entry/index.html',{'entries':entries})

def entry_view(request):
	if request.method == 'POST':
		form = EntryForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('entry:home')
	else:
		form = EntryForm()
	return render(request,'entry/entry.html',{'form':form})
    

entry/templates/entry/entry.html
{% extends 'base.html' %}
{% block content %}
    <title>Entry</title>
</head>
<body>
	<header>
		<div class="top-nav">
			<p class="intro-diary">Diary</p>
			
		</div>
	</header>

	<div class="container justify-content-center">
		<div class="jumbotron comment-cont">
			<form action="{% url 'entry:entr' %}" class="form-group" method="post">
				{% csrf_token %}
			  <label for="comment">Title: </label>
			   {{ form.name }}
			   <label for="comment">Diary Entry:</label>
			  {{ form.story }}
			  <input class="btn btn-default" type="submit" name="" value="Save">
			</form> 
			</div>
		</div>
	

	<footer class="navbar-fixed-bottom">
		<div class="bottom">
			<p>&copy; My Diary </p>
			<p>Copyright (c) 2020 All rights reserved</p>
		</div>
	</footer>

{% endblock %}

entry/templates/entry/index.html

{% extends 'base.html' %}
{% block content %}
    <title>My Diary</title>
</head>
<body>
	<header>
		<div class="top-nav">
			<p class="intro-diary">Diary</p>
			
		</div>
	</header>

	<div class="container justify-content-center">
	<div class="new-entry">
		<p><a href="{%url 'entry:entr' %}"> Add an Entry </a></p>
	</div>
		{% for entry in entries %}
			<div class="panel panel-default">
			  <div class="panel-heading">{{ entry.name }}</div>
			  <div class="panel-body">{{ entry.snippet }}</div>
			</div>
			{% endfor %}
	</div>

	<footer>
		<div class="bottom">
			<p>&copy; My Diary </p>
			<p>Copyright (c) 2020 All rights reserved</p>
		</div>
	</footer>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% block content %}
{% endblock %}

</body>
</html>